### PR TITLE
Some random changes

### PR DESCRIPTION
**Pull request by MyreMylar**
Look, a whole bunch of silly formatting changes and I messed with your theme file too.

Did you know you can put a little _ underscore in front of function parameters you aren't using yet to tell linters to stop bothering you? 

Well, you can.

### CODE REVIEW

**Comment by MyreMylar** [comment]
You don't need to actually merge this. Maybe, it breaks your build configuration setup I have no idea.

**Review by halfninja — COMMENTED** [review]
Aw tanks. I will probably keep the changes but revert the addition of src to imports, since it is the source root as discussed. It might be that including this folder name is the correct thing to do, and it just wants to be renamed from src to mygame or whatever.

**Comment by halfninja** [comment]
Does the src change work for you?
```
(venv) C:\Users\Nick\PycharmProjects\Game>python src\main.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "src\main.py", line 8, in <module>
    from src.cannon import Cannon
ModuleNotFoundError: No module named 'src'
```

**Comment by halfninja** [comment]
I've incorporated this into master now, minus the src changes, so I'll close this thingy. Tanks again

**Comment by halfninja** [comment]
With this PyCharm config it seems happy to treat src as the top of the world

image

**Pull request closed without merging**
